### ISSUE TITLE
Training issues with example 7-learning_embeddings_with_LTN.ipynb

### ISSUE THREAD

**Issue by paulsilvap** [bmxitalia/LTNtorch#1]
There seems to be a mismatch in the dimensions when training axioms 8, 9, 10. 
For axioms 8 and 10, Pytorch outputs:
```
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)
```
while for axiom 9,  ltn outputs:
```
ValueError: 'x' is not in list
```
Any advice on how to solve these issues?

**Comment by tommasocarraro** [comment]
Hi @paulsilvap,
I checked the example and saw the problem.

The problem was due to a deep copy that did not work properly inside the core of LTNtorch. So, it was impossible for you to solve the problem on your own since the errors were generated by internal functionalities.

Now, I fixed the issue and the example is working again. 

Thank you very much for reporting this.

**Comment by paulsilvap** [comment]
You're welcome @bmxitalia, thanks for the fix
